# This is a basic workflow to help you get started with Actions
name: Java CI with Maven

on:
  - push
  - pull_request
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - run: mvn install -DskipTests

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          target
  test:

    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts

    - run: mvn test


  publish:

    runs-on: ubuntu-latest
    needs: test
    steps:
    - run : echo "Publish the stuff!"
